# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DynamicPlotWidget
                                 A QGIS plugin
QGIS plugin to create a plot instance that updates dynamically.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-01-18
        copyright            : (C) 2024 by Caterina Giacomelli
        email                : c.giacomelli1@icloud.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MainPlugin class from file mainPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mainPlugin import MainPlugin
    return MainPlugin(iface)
